on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  preview-theme-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Preview Theme Changes
        uses: vcanales/action-wp-playground-pr-preview@9e8412e726b0dbc29eb58ceffbb4aca8e291c7e3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          base-branch: trunk
          single-theme: true
